<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加内容</title>
    <link rel="stylesheet" type="text/css" href="/css/jquery.page.js.css">
    <link rel="stylesheet" type="text/css" href="/css/contentManage.css">
    <SCRIPT src="/js/jquery-1.9.1.min.js" type="text/javascript"></SCRIPT>
    <SCRIPT src="/js/jquery.page.js" type="text/javascript"></SCRIPT>
</head>
<body>
<div class="common_box">
    <div class="search_div_form">
        <div class="holder"></div>
        <form action="/Addarticle/handler" method="post">
            <span>内容url:</span>
            <input type="text" name="content_url" placeholder="请提供要抓取内容的url地址" value="<?=$url?>"/>
            <input class="submit" type="submit" name="add_submit" value="添加" />
        </form>
        <div class="res_msg">
            <span class="info">返回信息：</span>
            <span class="ret"><?=$ret?></span>
        </div>
    </div>
    <div class="holder"></div>
</div>
</body>
</html>