<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加标签</title>
    <link rel="stylesheet" type="text/css" href="/css/jquery.page.js.css">
    <link rel="stylesheet" type="text/css" href="/css/contentManage.css">
    <SCRIPT src="/js/jquery-1.9.1.min.js" type="text/javascript"></SCRIPT>
    <SCRIPT src="/js/jquery.page.js" type="text/javascript"></SCRIPT>
    <script src="/js/jquery.cxselect.min.js"></script>
    <style>
      #tag_custom{
            padding: 1px;
      }
      .add_tag{
        margin: 10px 20px 0px 80px;
      }
    </style>
</head>

<body>
	<div class="common_box">
        <div class="search_div">
        	
            <form id="tag_custom" action="/addtag/add" method="post">
              <table class="table editTable common_margin">
                <tr></tr>
                <tr>
                  <td>标签名称:</td>
                  <td>
                     <input type="text" name="tag_name" placeholder="请输入标签名称"/>
                  </td>
                </tr>
                <tr>
                  <td>标签级别:</td>
                  <td>
                    <select class="first" disabled="disabled" name="tag_level" id="tag_level">
                    </select>
                  </td>
                </tr>
                <tr>
                  <td>选择游戏:</td>
                  <td>
                    <select class="second" disabled="disabled" name="tag_id_level1" id="tag_id_level1">
                    </select>
                  </td>
                </tr>
                <tr>
                  <td>对应二级标签:</td>
                  <td>
                    <select class="third" disabled="disabled" name="tag_id_level2" id="tag_id_level2">
                    </select>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    <input class="submit add_tag" type="submit" name="editsubmit" value="添加"/>
                  </td>
                </tr>
              </table>
            </form>
        </div>
        <div class="holder"></div>
    </div>
<script type="text/javascript">
$('#tag_custom').cxSelect({
  selects: ['first', 'second', 'third'],
  required: true,
  url: <?php echo $level_list;?>
});
</script>
</body>
</html>