<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" href="/css/content.css" />
	<link rel="stylesheet" href="/css/contentManage.css" />
	<SCRIPT src="/js/jquery-1.9.1.min.js" type="text/javascript"></SCRIPT>
    <SCRIPT type="text/javascript" src="/js/content.js"></SCRIPT>
	<title>文章详情</title>
	<style>
		.select{
			height: 25px;
		    border: 1px solid #e1e0e0;
		    width: 150px;
		    margin: 10px 20px 10px 10px;
		    background-color: #ebebeb;
		}
	</style>
</head>
<body>
	<div class="content common_box">
		<div class="zone1 ">
			<table class="table editTable common_margin">
				<tr>
					<td colspan="4"><div class="a_title">标题</div></td>
				</tr>
				<tr>
					<td colspan="4"><input type="text" name="tag" id="articleTitle" value="<?=$article['title']?>" placeholder="请输入标题" /></td>
				</tr>
				<tr>
					<td colspan="4"><div class="a_title">摘要</div></td>
				</tr>
				<tr>
					<td colspan="4"><textarea name="summary" id="summary" cols="30" rows="10" placeholder="请输入摘要"><?=$article['summary']?></textarea></td>
				</tr>
				<tr>
					<td width="120"><span class="editMargin">原创时间：</span></td>
					<td><span class="editMargin" id="ctime"><?=date('Y-m-d H:i:s', $article['ctime'])?></span></td>
				</tr>

				<tr>
					<td><span class="editMargin">内容类型：</span></td>
					<td colspan="3">
						<select name="contentType" id="contentType"  class="select">
							<option value="0">请选择</option>
							<?php
							if($article_types):
								foreach($article_types as $type):
									?>
									<option value="<?=$type['a_t_id']?>" <?php if($article['a_t_id'] == $type['a_t_id']){echo "selected";}?>><?=$type['name']?></option>
									<?php
								endforeach;
							endif;
							?>
						</select>
					</td>
				</tr>
				<tr>
					<td><span class="editMargin">内容形式：</span></td>
					<td colspan="3">
						<select name="contentStyle" id="contentStyle"  class="select">
							<option value="0">请选择</option>
							<?php
							if($article_forms):
								foreach($article_forms as $form):
									?>
									<option value="<?=$form['a_f_id']?>" <?php if($article['a_f_id'] == $form['a_f_id']){echo "selected";}?>><?=$form['name']?></option>
									<?php
								endforeach;
							endif;
							?>
						</select>
					</td>
				</tr>
				<tr>
					<td colspan="4"><a href="#" class="common_a" target="_blank">链接原文</a></td>
				</tr>
				<tr>
					<td colspan="4" align="right" class="buttonTd">
						<input type="submit" name="save" value="保存" id="updateArticleContent" class="editButton submit"/>
					</td>
				</tr>

				<tr>
					<td colspan="4"><hr /></td>
				</tr>
				<tr>
					<td><span class="editMargin">一级标签：</span></td>
					<td colspan="3">
						<select name="firstClassTag" id="firstClassTag" class="select">
							<option value="0">请选择一级标签</option>
							<option value="1" selected="selected">一级标签1</option>
							<option value="2" >一级标签2</option>
						</select>
					</td>
				</tr>
				<tr>
					<td><span class="editMargin">二级标签：</span></td>
					<td colspan="3" id="secondClassTagCollect">
						<input type="checkbox" name="secondClassTag1" value="EDG:1" tag="1" id="secondClassTag1"/>&nbsp;<label for="secondClassTag1">EDG：1</label>&nbsp;&nbsp;
						<input type="checkbox" name="secondClassTag2" value="ROX:0.3" tag="1" id="secondClassTag2"/>&nbsp;<label for="secondClassTag2">ROX：0.3</label> &nbsp;&nbsp;
					</td>
				</tr>
				<tr>
					<td><span class="editMargin">三级标签：</span></td>
					<td colspan="3" id="secondClassTagCollect">
						<input type="checkbox" name="secondClassTag1" value="EDG:1" tag="1" id="secondClassTag1"/>&nbsp;<label for="secondClassTag1">EDG：1</label>&nbsp;&nbsp;
						<input type="checkbox" name="secondClassTag2" value="ROX:0.3" tag="1" id="secondClassTag2"/>&nbsp;<label for="secondClassTag2">ROX：0.3</label> &nbsp;&nbsp;
					</td>
				</tr>
				<tr>
					<td><span class="editMargin">添加二级标签：</span></td>
					<td>
						<select name="tag2add" id="tag2add"  class="select">
							<option value="0">请选择二级标签</option>
							<option value="标签1">标签1</option>
							<option value="标签2">标签2</option>
						</select>
					</td>
					<td colspan="2">
						<input type="text" name="tagScore" id="tagScore" placeholder="标签得分"/>&nbsp;&nbsp;&nbsp;&nbsp;
					</td>
				</tr>

				<tr>
					<td><span class="editMargin">添加三级标签：</span></td>
					<td>
						<select name="tag2add" id="tag2add"  class="select">
							<option value="0">请选择二级标签</option>
							<option value="标签1">标签1</option>
							<option value="标签2">标签2</option>
						</select>
					</td>
					<td>
						<select name="tag2add" id="tag2add"  class="select">
							<option value="0">请选择三级标签</option>
							<option value="标签1">标签1</option>
							<option value="标签2">标签2</option>
						</select>
					</td>
					<td>
						<input width="20" type="text" name="tagScore" placeholder="标签得分"/>
					</td>
				</tr>
				<tr>
					<td colspan="4" align="right" class="buttonTd">
						<input type="submit" name="save" value="保存" id="updateArticletag" class="editButton submit"/>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<input type="hidden" id="aid" value="<?=$article['aid']?>" />
</body>
</html>