<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>游趣-后台管理系统</title>
    <link rel="stylesheet" type="text/css" href="/css/main.css">
    <SCRIPT src="/js/jquery-1.9.1.min.js" type="text/javascript"></SCRIPT>
    <SCRIPT type="text/javascript" src="/js/main.js"></SCRIPT>
</head>
<body>

    <!-- 头部 -->
    <div class="header clear">
        <div class="header_div1">
            <span class="header_span1">游趣-运营后台管理系统</span>
        </div>
        <div class="header_div2">
            <a class="div2_a1 a_common1" href="#">账号:&nbsp;&nbsp; <?=$userName?></a>
            <a class="div2_a2 a_common1" href="/login?from=logout">退出 !</a>
        </div>
    </div>

    <!-- 主体 -->
    <div class="main clear">
        <div class="left">
            <ul>
                <?php
                if(! empty($auth)):
                        foreach ($auth as $key => $item):
                            if(count($item) == 1):
                ?>
                                <li><a href="<?=$item[0]['url']?>" target="main_show"><?=$class[$key]?></a><input type="hidden" value="<?=$class[$key]?>"></li>

                <?php
                            else:
                ?>
                                <li class="toggle_li"><a><?=$class[$key]?></a><input type="hidden" value="none">
                                    <ul>
                <?php
                                foreach ($item as $it):
                ?>
                                        <li><a href="<?=$it['url']?>" target="main_show"><?=$it['authName']?></a><input type="hidden" value="<?=$class[$key]?> > <?=$it['authName']?>"></li>
                <?php
                                endforeach;
                ?>
                                    </ul>
                                </li>
                <?php
                            endif;
                    endforeach;
                endif;
                ?>



                <!--<li><a href="/contentManage" target="main_show">内容管理</a><input type="hidden" value="内容管理"></li>
                <li class="toggle_li"><a>其他操作</a><input type="hidden" value="none">
                    <ul>
                        <li><a href="/changeKnowledgeDb" target="main_show">更新知识库</a><input type="hidden" value="其他操作 > 更新知识库"></li>
                        <li><a href="/addArticle" target="main_show">添加内容</a><input type="hidden" value="其他操作 > 添加内容"></li>
                        <li><a href="/addTag" target="main_show">添加标签</a><input type="hidden" value="其他操作 > 添加标签"></li>
                        <li><a href="/addAlias" target="main_show">添加别名</a><input type="hidden" value="其他操作 > 添加别名"></li>
                    </ul>
                </li>
                <li><a href="/authManage" target="main_show">权限管理</a><input type="hidden" value="权限管理"></li>
                -->
            </ul>
        </div>
        <div class="right">
            <div>当前位置: &nbsp;&nbsp;&nbsp;&nbsp;<a class="user_position"><b>内容管理</b></a></div>
            <div>
                <iframe id="iframepage" name="main_show" src="/contentManage" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div>
        </div>
    </div>
</body>
</html>